sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
install:
  - npm install -g firebase-tools
scripts:
  - echo "Install dependencies"
  - yarn install
  - echo "Linter"
  - yarn lint
  - echo "Building"
  - yarn build
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  on:
    branch: master
  project: "devandfest"